export const productsData = [
  {
    id: 1,
    name: "Coat",
    price: "200",
    color: "red",
    size: ["M", "L"],
    description: "this is coat",
    quantity: 1,
  },
  {
    id: 2,
    name: "Hat",
    price: "300",
    color: "orange",
    size: ["M", "L", "XXL"],
    description: "this is hat",
    quantity: 1,
  },
  {
    id: 3,
    name: "Pants",
    price: "450",
    color: "black",
    size: ["L", "XL", "XXL"],
    description: "this is pants",
    quantity: 1,
  },
  {
    id: 4,
    name: "Jacket",
    price: "180",
    color: "yellow",
    size: ["M", "XL", "XXL"],
    description: "this is jacket",
    quantity: 1,
  },
  {
    id: 5,
    name: "Shawl",
    price: "180",
    color: "blue",
    size: ["L"],
    description: "this is shawl",
    quantity: 1,
  },
  {
    id: 6,
    name: "Gloves",
    price: "67",
    color: "pinck",
    size: ["XL"],
    description: "this is gloves",
    quantity: 1,
  },
  {
    id: 7,
    name: "Shirt",
    price: "115",
    color: "sky blue",
    size: ["M"],
    description: "this is shirt",
    quantity: 1,
  },
];
